// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_transfer_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_transfer_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_transfer_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_transfer_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_transfer_2eproto;
namespace omnibox {
class FileChunkUploadRequest;
struct FileChunkUploadRequestDefaultTypeInternal;
extern FileChunkUploadRequestDefaultTypeInternal _FileChunkUploadRequest_default_instance_;
class FileChunkUploadResponse;
struct FileChunkUploadResponseDefaultTypeInternal;
extern FileChunkUploadResponseDefaultTypeInternal _FileChunkUploadResponse_default_instance_;
}  // namespace omnibox
PROTOBUF_NAMESPACE_OPEN
template<> ::omnibox::FileChunkUploadRequest* Arena::CreateMaybeMessage<::omnibox::FileChunkUploadRequest>(Arena*);
template<> ::omnibox::FileChunkUploadResponse* Arena::CreateMaybeMessage<::omnibox::FileChunkUploadResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace omnibox {

// ===================================================================

class FileChunkUploadRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:omnibox.FileChunkUploadRequest) */ {
 public:
  inline FileChunkUploadRequest() : FileChunkUploadRequest(nullptr) {}
  ~FileChunkUploadRequest() override;
  explicit constexpr FileChunkUploadRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FileChunkUploadRequest(const FileChunkUploadRequest& from);
  FileChunkUploadRequest(FileChunkUploadRequest&& from) noexcept
    : FileChunkUploadRequest() {
    *this = ::std::move(from);
  }

  inline FileChunkUploadRequest& operator=(const FileChunkUploadRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileChunkUploadRequest& operator=(FileChunkUploadRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileChunkUploadRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileChunkUploadRequest* internal_default_instance() {
    return reinterpret_cast<const FileChunkUploadRequest*>(
               &_FileChunkUploadRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FileChunkUploadRequest& a, FileChunkUploadRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(FileChunkUploadRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileChunkUploadRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileChunkUploadRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FileChunkUploadRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FileChunkUploadRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const FileChunkUploadRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FileChunkUploadRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "omnibox.FileChunkUploadRequest";
  }
  protected:
  explicit FileChunkUploadRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFileNameFieldNumber = 1,
    kDataFieldNumber = 3,
    kOffsetFieldNumber = 2,
    kTotalSizeFieldNumber = 5,
    kIsEofFieldNumber = 4,
  };
  // string file_name = 1;
  void clear_file_name();
  const std::string& file_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_file_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_file_name();
  PROTOBUF_NODISCARD std::string* release_file_name();
  void set_allocated_file_name(std::string* file_name);
  private:
  const std::string& _internal_file_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_file_name(const std::string& value);
  std::string* _internal_mutable_file_name();
  public:

  // bytes data = 3;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // int64 offset = 2;
  void clear_offset();
  int64_t offset() const;
  void set_offset(int64_t value);
  private:
  int64_t _internal_offset() const;
  void _internal_set_offset(int64_t value);
  public:

  // int64 total_size = 5;
  void clear_total_size();
  int64_t total_size() const;
  void set_total_size(int64_t value);
  private:
  int64_t _internal_total_size() const;
  void _internal_set_total_size(int64_t value);
  public:

  // bool is_eof = 4;
  void clear_is_eof();
  bool is_eof() const;
  void set_is_eof(bool value);
  private:
  bool _internal_is_eof() const;
  void _internal_set_is_eof(bool value);
  public:

  // @@protoc_insertion_point(class_scope:omnibox.FileChunkUploadRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr file_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  int64_t offset_;
  int64_t total_size_;
  bool is_eof_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_transfer_2eproto;
};
// -------------------------------------------------------------------

class FileChunkUploadResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:omnibox.FileChunkUploadResponse) */ {
 public:
  inline FileChunkUploadResponse() : FileChunkUploadResponse(nullptr) {}
  ~FileChunkUploadResponse() override;
  explicit constexpr FileChunkUploadResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FileChunkUploadResponse(const FileChunkUploadResponse& from);
  FileChunkUploadResponse(FileChunkUploadResponse&& from) noexcept
    : FileChunkUploadResponse() {
    *this = ::std::move(from);
  }

  inline FileChunkUploadResponse& operator=(const FileChunkUploadResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileChunkUploadResponse& operator=(FileChunkUploadResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileChunkUploadResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileChunkUploadResponse* internal_default_instance() {
    return reinterpret_cast<const FileChunkUploadResponse*>(
               &_FileChunkUploadResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(FileChunkUploadResponse& a, FileChunkUploadResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(FileChunkUploadResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileChunkUploadResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileChunkUploadResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FileChunkUploadResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FileChunkUploadResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const FileChunkUploadResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FileChunkUploadResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "omnibox.FileChunkUploadResponse";
  }
  protected:
  explicit FileChunkUploadResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kNextOffsetFieldNumber = 3,
    kSuccessFieldNumber = 1,
  };
  // string message = 2;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // int64 next_offset = 3;
  void clear_next_offset();
  int64_t next_offset() const;
  void set_next_offset(int64_t value);
  private:
  int64_t _internal_next_offset() const;
  void _internal_set_next_offset(int64_t value);
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:omnibox.FileChunkUploadResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  int64_t next_offset_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_transfer_2eproto;
};
// ===================================================================

class TransferService_Stub;

class TransferService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline TransferService() {};
 public:
  virtual ~TransferService();

  typedef TransferService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void UploadChunk(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::omnibox::FileChunkUploadRequest* request,
                       ::omnibox::FileChunkUploadResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(TransferService);
};

class TransferService_Stub : public TransferService {
 public:
  TransferService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  TransferService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~TransferService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements TransferService ------------------------------------------

  void UploadChunk(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::omnibox::FileChunkUploadRequest* request,
                       ::omnibox::FileChunkUploadResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(TransferService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FileChunkUploadRequest

// string file_name = 1;
inline void FileChunkUploadRequest::clear_file_name() {
  file_name_.ClearToEmpty();
}
inline const std::string& FileChunkUploadRequest::file_name() const {
  // @@protoc_insertion_point(field_get:omnibox.FileChunkUploadRequest.file_name)
  return _internal_file_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileChunkUploadRequest::set_file_name(ArgT0&& arg0, ArgT... args) {
 
 file_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:omnibox.FileChunkUploadRequest.file_name)
}
inline std::string* FileChunkUploadRequest::mutable_file_name() {
  std::string* _s = _internal_mutable_file_name();
  // @@protoc_insertion_point(field_mutable:omnibox.FileChunkUploadRequest.file_name)
  return _s;
}
inline const std::string& FileChunkUploadRequest::_internal_file_name() const {
  return file_name_.Get();
}
inline void FileChunkUploadRequest::_internal_set_file_name(const std::string& value) {
  
  file_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* FileChunkUploadRequest::_internal_mutable_file_name() {
  
  return file_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* FileChunkUploadRequest::release_file_name() {
  // @@protoc_insertion_point(field_release:omnibox.FileChunkUploadRequest.file_name)
  return file_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void FileChunkUploadRequest::set_allocated_file_name(std::string* file_name) {
  if (file_name != nullptr) {
    
  } else {
    
  }
  file_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), file_name,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (file_name_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    file_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:omnibox.FileChunkUploadRequest.file_name)
}

// int64 offset = 2;
inline void FileChunkUploadRequest::clear_offset() {
  offset_ = int64_t{0};
}
inline int64_t FileChunkUploadRequest::_internal_offset() const {
  return offset_;
}
inline int64_t FileChunkUploadRequest::offset() const {
  // @@protoc_insertion_point(field_get:omnibox.FileChunkUploadRequest.offset)
  return _internal_offset();
}
inline void FileChunkUploadRequest::_internal_set_offset(int64_t value) {
  
  offset_ = value;
}
inline void FileChunkUploadRequest::set_offset(int64_t value) {
  _internal_set_offset(value);
  // @@protoc_insertion_point(field_set:omnibox.FileChunkUploadRequest.offset)
}

// bytes data = 3;
inline void FileChunkUploadRequest::clear_data() {
  data_.ClearToEmpty();
}
inline const std::string& FileChunkUploadRequest::data() const {
  // @@protoc_insertion_point(field_get:omnibox.FileChunkUploadRequest.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileChunkUploadRequest::set_data(ArgT0&& arg0, ArgT... args) {
 
 data_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:omnibox.FileChunkUploadRequest.data)
}
inline std::string* FileChunkUploadRequest::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:omnibox.FileChunkUploadRequest.data)
  return _s;
}
inline const std::string& FileChunkUploadRequest::_internal_data() const {
  return data_.Get();
}
inline void FileChunkUploadRequest::_internal_set_data(const std::string& value) {
  
  data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* FileChunkUploadRequest::_internal_mutable_data() {
  
  return data_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* FileChunkUploadRequest::release_data() {
  // @@protoc_insertion_point(field_release:omnibox.FileChunkUploadRequest.data)
  return data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void FileChunkUploadRequest::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (data_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:omnibox.FileChunkUploadRequest.data)
}

// bool is_eof = 4;
inline void FileChunkUploadRequest::clear_is_eof() {
  is_eof_ = false;
}
inline bool FileChunkUploadRequest::_internal_is_eof() const {
  return is_eof_;
}
inline bool FileChunkUploadRequest::is_eof() const {
  // @@protoc_insertion_point(field_get:omnibox.FileChunkUploadRequest.is_eof)
  return _internal_is_eof();
}
inline void FileChunkUploadRequest::_internal_set_is_eof(bool value) {
  
  is_eof_ = value;
}
inline void FileChunkUploadRequest::set_is_eof(bool value) {
  _internal_set_is_eof(value);
  // @@protoc_insertion_point(field_set:omnibox.FileChunkUploadRequest.is_eof)
}

// int64 total_size = 5;
inline void FileChunkUploadRequest::clear_total_size() {
  total_size_ = int64_t{0};
}
inline int64_t FileChunkUploadRequest::_internal_total_size() const {
  return total_size_;
}
inline int64_t FileChunkUploadRequest::total_size() const {
  // @@protoc_insertion_point(field_get:omnibox.FileChunkUploadRequest.total_size)
  return _internal_total_size();
}
inline void FileChunkUploadRequest::_internal_set_total_size(int64_t value) {
  
  total_size_ = value;
}
inline void FileChunkUploadRequest::set_total_size(int64_t value) {
  _internal_set_total_size(value);
  // @@protoc_insertion_point(field_set:omnibox.FileChunkUploadRequest.total_size)
}

// -------------------------------------------------------------------

// FileChunkUploadResponse

// bool success = 1;
inline void FileChunkUploadResponse::clear_success() {
  success_ = false;
}
inline bool FileChunkUploadResponse::_internal_success() const {
  return success_;
}
inline bool FileChunkUploadResponse::success() const {
  // @@protoc_insertion_point(field_get:omnibox.FileChunkUploadResponse.success)
  return _internal_success();
}
inline void FileChunkUploadResponse::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void FileChunkUploadResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:omnibox.FileChunkUploadResponse.success)
}

// string message = 2;
inline void FileChunkUploadResponse::clear_message() {
  message_.ClearToEmpty();
}
inline const std::string& FileChunkUploadResponse::message() const {
  // @@protoc_insertion_point(field_get:omnibox.FileChunkUploadResponse.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileChunkUploadResponse::set_message(ArgT0&& arg0, ArgT... args) {
 
 message_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:omnibox.FileChunkUploadResponse.message)
}
inline std::string* FileChunkUploadResponse::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:omnibox.FileChunkUploadResponse.message)
  return _s;
}
inline const std::string& FileChunkUploadResponse::_internal_message() const {
  return message_.Get();
}
inline void FileChunkUploadResponse::_internal_set_message(const std::string& value) {
  
  message_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* FileChunkUploadResponse::_internal_mutable_message() {
  
  return message_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* FileChunkUploadResponse::release_message() {
  // @@protoc_insertion_point(field_release:omnibox.FileChunkUploadResponse.message)
  return message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void FileChunkUploadResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (message_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:omnibox.FileChunkUploadResponse.message)
}

// int64 next_offset = 3;
inline void FileChunkUploadResponse::clear_next_offset() {
  next_offset_ = int64_t{0};
}
inline int64_t FileChunkUploadResponse::_internal_next_offset() const {
  return next_offset_;
}
inline int64_t FileChunkUploadResponse::next_offset() const {
  // @@protoc_insertion_point(field_get:omnibox.FileChunkUploadResponse.next_offset)
  return _internal_next_offset();
}
inline void FileChunkUploadResponse::_internal_set_next_offset(int64_t value) {
  
  next_offset_ = value;
}
inline void FileChunkUploadResponse::set_next_offset(int64_t value) {
  _internal_set_next_offset(value);
  // @@protoc_insertion_point(field_set:omnibox.FileChunkUploadResponse.next_offset)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace omnibox

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_transfer_2eproto
